apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels: 
    owner: Ivanov Alexander
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.8.3
        ports:
        - containerPort: 8200