apiVersion: apps/v1
kind: Deployment
metadata:
  name: itdt-contained-frontend
  labels:
    owner: Ivanov_Alexander
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itdt-contained-frontend
  template:
    metadata:
      labels:
        app: itdt-contained-frontend
    spec:
      containers:
      - name: itdt-contained-frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
          - name: REACT_APP_USERNAME
            value: "Ivanov Alexander"
          - name: REACT_APP_COMPANY_NAME
            value: "ITMO University"        
        ports:
        - containerPort: 3000
